apiVersion: v1
kind: BuildConfig
metadata:
  name: rbarcia.java-demo
  labels:
    app: java-demo
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/rbarcia/java-demo.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev
        - name: BRANCH
          value: master
